### ISSUE TITLE
Broken Link to Code of Conduct

### ISSUE THREAD

**Issue by JoeLewisB** [CodeForBaltimore/codeforbaltimore.org#50]
https://github.com/CodeForBaltimore/codeforbaltimore.org/blob/061a2c7c5dc513ae9c0fd6e3e21e1768eae5e907/pages/get-involved/index.vue#L44

Link goes to https://codeforbaltimore.org/get-involved/code-for-conduct.html and should go to https://codeforbaltimore.org/get-involved/code-of-conduct.html

**Comment by revjtanton** [comment]
Should go to https://codeforbaltimore.org/code-of-conduct
